services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: livemeet2024
      POSTGRES_USER: postgres
      POSTGRES_DB: livemeet
      POSTGRES_HOST_AUTH_METHOD: md5
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
